### ISSUE TITLE
Issue with 00035221.npy

### ISSUE THREAD

**Issue by Shreyas-NR** [oppo-us-research/PoP-Net#5]
Hi @yuliangguo @oppo-us-research 

![image](https://user-images.githubusercontent.com/58805235/187569025-4635d084-abd5-4e08-bf1b-5d102ee3a260.png)

Unable to load 00035221.npy file

![image](https://user-images.githubusercontent.com/58805235/187569301-2fc46430-63ee-4d15-93c6-46fcb1494448.png)

Could you please help me with this file? This is stopping me from training my model with the dataset.

**Comment by calvindu95** [comment]
> 

Hi, we are working on this, I will upload this file today, and you could continue your training. We would fix the dataset and reseed it this week.

**Comment by calvindu95** [comment]
> Hi @yuliangguo @oppo-us-research
> 
> ![image](https://user-images.githubusercontent.com/58805235/187569025-4635d084-abd5-4e08-bf1b-5d102ee3a260.png)
> 
> Unable to load 00035221.npy file
> 
> ![image](https://user-images.githubusercontent.com/58805235/187569301-2fc46430-63ee-4d15-93c6-46fcb1494448.png)
> 
> Could you please help me with this file? This is stopping me from training my model with the dataset.

Here is the original file. 
[00035221.zip](https://github.com/oppo-us-research/PoP-Net/files/9552539/00035221.zip)

**Comment by yuliangguo** [comment]
Hey guys, it seems that I don’t have any local copy of the data. I am not
sure if you can find the undamaged file on the server machine or some
desktop. If there is no luck, it would not hurt to just remove this sample
and it’s associated label from the training set. Since the training samples
are not equally sampled, where only keep those qualified ones are kept,
 deleting one more does not hurt.

**Comment by yuliangguo** [comment]
@Shreyas-NR  Hi. Could I ask whether you still have a copy of this dataset locally? Since the company has no maintainess of the downloading, could I ask you a favor to share the dataset back to us?

**Comment by Shreyas-NR** [comment]
@yuliangguo, Sorry for the delayed response. 
I have the copy of dataset with me. 
I'm unsure of the best way to share it. Could you please let me know the same?


Best regards,
Shreyas

**Comment by yuliangguo** [comment]
Hi @Shreyas-NR,

Thanks a lot for your reply. Since the dataset has Apache Licence 2.0,
which allows it to be distributed, the best way should be uploading the
dataset to huggingface directly.  When you have uploaded the dataset there,
you could either let us know the link, so we can directly refer to it for
everyone else to download from. Or you could transfer the ownership to me,
my huggingface account name is "yuliangguo". As long as we know,
huggingface can host dataset free, as long as it is made public.

We will truly appreciate your help.

**Comment by Shreyas-NR** [comment]
@yuliangguo 
Each file size is 22.5GB, .zip file type

I'm unable to upload them on huggingface
Any alternative solution?

**Comment by yuliangguo** [comment]
> @yuliangguo Each file size is 22.5GB, .zip file type
> 
> I'm unable to upload them on huggingface Any alternative solution?

Then it seems really complicated. Based on their rule https://huggingface.co/docs/hub/en/repositories-recommendations
They can host 300GB with 20GB per file. Could you try emailing [datasets@huggingface.co] as they said it might give you some alternative way.  I am really sorry to put such extra effort on your side.
